validates flight dates against actuals served
PRX/grove.prx.org pull request #224
Opened 2020-07-09 17:29 UTC by sandikbarr

Validates the flight start and end dates to be within the dates that actuals have been served. It doesn't stop the preview request on flight date change, which also gives the same error, but it does prevent the flight from being saved because of an invalid form.

Flight form fields were getting touched reset on form updates because of the use of `reset` in the incoming form updates, so the validation errors would flash up but then go away. I changed that `reset` to `patchValue` to resolve this. Maybe when the flight id changes, the form controls could be reset when updating the values to the routed flight if it hasn't been changed, but probably the correct way to have done this would have been to have all the flight forms in a single parent form group instead of swapping out the one form's values.

2020-07-09 17:31 UTC, sandikbarr commented on src/app/campaign/flight/flight-form-control-container.component.ts
> -    // reset the form
if we use `reset` it also resets the controls to pristine, which doesn't seem like something we want on every update cycle

2020-07-10 18:42 UTC, rpeterman-gp requested changes
Looks good. Only thing I found was a console.log statement we probably don't need in prod.

2020-07-10 18:42 UTC, rpeterman-gp commented on src/app/campaign/store/selectors/flight-days.selectors.ts
> +    console.log({ startAt: startAt.date, endAt: endAt.date });
Do we need this console.log?

2020-07-10 19:06 UTC, sandikbarr commented on src/app/campaign/store/selectors/flight-days.selectors.ts
> +    console.log({ startAt: startAt.date, endAt: endAt.date });
oops dang, will remove!!

2020-07-10 20:05 UTC, rpeterman-gp approved these changes

2020-07-10 20:59 UTC, merged